import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
          <div className="bg-gray-200 flex">
            <div className='p-2'>
            <Navbar />
            </div>
           
            <main className="flex-1 p-8">{children}</main>
          </div>
       
      </body>
    </html>
  );
}
